### ISSUE TITLE
minor code quality issue

### ISSUE THREAD

**Issue by okkhoy** [AY2324S2-CS2113T-T09-1/tp#222]
@annoy-o-mus 
- `src/main/java/meditracker/storage/FilePathChecker.java` -> `containsValidRoot` method `assert false` will already exit the code, right?

**Comment by annoy-o-mus** [comment]
```
if (root == null) {
    assert false;
    return false;
}
```

While that is true, there is a few reasons why this chunk is like this. one is that that root of the filesystem should also be present in the `root` variable (it should never be null) and that the return is also present in case the flag to check for assert statements are removed.

Still, asserts can cause crashes and I guess given the scope of the project, this unexpected behaviour can be handled more gracefully instead of just crashing.
